language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=proteindb/
after_success:
  - coveralls